# Default values for crusoe-csi-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
driverName: "csi.crusoe.ai"
image:
  repository: ghcr.io/crusoecloud/crusoe-csi-driver
  tag: "main"

crusoe:
  projectID: ""

secrets:
  crusoeApiKeys:
    secretName: "crusoe-api-keys"
controller:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi

node:
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi
